title: OpenControl
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
base_font: nunito-sans
palette: orange
header:
  logo_img_alt: Logo
  has_nav: true
  nav_links:
    - label: About
      url: about
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: left
      new_window: false
      no_follow: false
      type: action
    - label: Projects
      url: projects
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: left
      new_window: false
      no_follow: false
      type: action
    - label: Participate
      url: /participate
      style: link
    - label: Members
      url: 'about#members'
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: left
      new_window: false
      no_follow: false
      type: action
    - label: Blog
      url: blog
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: left
      new_window: false
      no_follow: false
      type: action
  logo_img: images/oclogo_small.png
footer:
  sections:
    - type: footer_text
      image: images/thoughtful-goose.png
      image_url: /
      image_alt: Footer logo
      content: |
        Security, not obsurity
    - type: footer_nav
      title: OpenControl
      nav_links:
        - label: About Us
          url: /about
          style: link
        - label: Blog
          url: /blog
          style: link
        - label: Sign Up
          url: /signup
          style: link
        - label: Contact
          url: /contact
          style: link
    - type: footer_nav
      title: Community
      nav_links:
        - label: GitHub
          url: 'https://github.com/opencontrol/discuss'
          style: link
          has_icon: true
          icon: github
          icon_position: left
    - type: footer_form
      title: Contact Us
      content: Stay up to date with our latest developments.
      form_id: contactForm
      hide_labels: true
      form_fields:
        - input_type: email
          name: email
          label: Email
          default_value: Enter email address
          is_required: true
      submit_label: Subscribe
  has_nav: true
  nav_links:
    - label: Privacy Policy
      url: /privacy-policy
      style: link
    - label: Code of Conduct
      url: privacy-policy
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: left
      new_window: false
      no_follow: false
      type: action
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=azimuth&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
